export interface DetailedPlace {
  placeId: string
  mainText: string
  secondaryText: string
  fullText: string
  types: string[]
  lat: number
  lng: number
  category: 'cafe' | 'housing' | 'mall' | 'campus' | 'hospital' | 'transit' | 'police'
}

export const JALUKBARI_AND_GUWAHATI_DIRECTORY: DetailedPlace[] = [
  // ==========================================
  // 1. JALUKBARI & WEST GUWAHATI CAFES & DINING
  // ==========================================
  {
    placeId: 'jaluk-cafe-1',
    mainText: 'The Hub Cafe & Fast Food',
    secondaryText: 'Near Jalukbari Rotary, NH-27, Guwahati 781014',
    fullText: 'The Hub Cafe & Fast Food, Jalukbari, Guwahati',
    types: ['cafe', 'food', 'restaurant'],
    lat: 26.151,
    lng: 91.666,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-2',
    mainText: 'Gauhati University Campus Canteen & Nescafe Point',
    secondaryText: 'GU Main Gate, Jalukbari, Guwahati 781014',
    fullText: 'GU Campus Canteen & Nescafe, Jalukbari, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.153,
    lng: 91.663,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-3',
    mainText: 'Brahmaputra Riverview Cafe & Bistro',
    secondaryText: 'Kamakhyanagar, Pandu Ghat Road, Guwahati 781012',
    fullText: 'Brahmaputra Riverview Cafe, Pandu, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.168,
    lng: 91.692,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-4',
    mainText: 'Radisson Blu Cafe & Great Kabab Factory',
    secondaryText: 'NH-37, Gotanagar, Jalukbari, Guwahati 781033',
    fullText: 'Radisson Blu Hotel & Cafe, Gotanagar, Jalukbari',
    types: ['cafe', 'restaurant', 'food'],
    lat: 26.1415,
    lng: 91.688,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-5',
    mainText: 'Highway Treat Cafe & Family Dhaba',
    secondaryText: 'Tetelia Highway, Jalukbari, Guwahati 781033',
    fullText: 'Highway Treat Cafe, Tetelia, Jalukbari',
    types: ['cafe', 'restaurant'],
    lat: 26.143,
    lng: 91.674,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-6',
    mainText: 'Jalukbari Chai & Roll Corner',
    secondaryText: 'Jalukbari Market Road, Guwahati 781014',
    fullText: 'Jalukbari Chai & Roll Corner, Jalukbari',
    types: ['cafe', 'food'],
    lat: 26.1505,
    lng: 91.668,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-7',
    mainText: 'Adabari Food Court & Bakers',
    secondaryText: 'Adabari Tiniali, AT Road, Guwahati 781014',
    fullText: 'Adabari Food Court, Adabari Tiniali, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.155,
    lng: 91.685,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-8',
    mainText: 'The Beans Cafe & Bistro',
    secondaryText: 'GS Road, Bhangagarh, Guwahati 781005',
    fullText: 'The Beans Cafe & Bistro, GS Road, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.161,
    lng: 91.768,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-9',
    mainText: '11th Avenue Cafe Bistro',
    secondaryText: 'Dighalipukhuri East, Uzan Bazaar, Guwahati 781001',
    fullText: '11th Avenue Cafe Bistro, Uzan Bazaar, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.188,
    lng: 91.752,
    category: 'cafe',
  },
  {
    placeId: 'jaluk-cafe-10',
    mainText: 'Cafe Hendrix',
    secondaryText: 'Down Town, GS Road, Rukmini Gaon, Guwahati 781022',
    fullText: 'Cafe Hendrix, Down Town, GS Road, Guwahati',
    types: ['cafe', 'food'],
    lat: 26.136,
    lng: 91.798,
    category: 'cafe',
  },

  // ========================================================
  // 2. JALUKBARI & WEST GUWAHATI HOUSING SOCIETIES & FLATS
  // ========================================================
  {
    placeId: 'jaluk-soc-1',
    mainText: 'Sundarbari Residential Housing Society',
    secondaryText: 'Sundarbari, Jalukbari, Guwahati 781014',
    fullText: 'Sundarbari Housing Society, Jalukbari, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.157,
    lng: 91.658,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-2',
    mainText: 'Gauhati University Faculty & Staff Housing Colony',
    secondaryText: 'Gauhati University Campus, Jalukbari 781014',
    fullText: 'GU Faculty Housing Colony, Jalukbari, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.151,
    lng: 91.661,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-3',
    mainText: 'AEC Faculty Quarters & Staff Colony',
    secondaryText: 'Assam Engineering College Campus, Jalukbari 781013',
    fullText: 'AEC Faculty Housing Colony, Jalukbari, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.143,
    lng: 91.662,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-4',
    mainText: 'Tetelia Green Enclave & Housing Society',
    secondaryText: 'Tetelia, NH-37 Bypass, Jalukbari, Guwahati 781033',
    fullText: 'Tetelia Green Enclave Housing Society, Jalukbari',
    types: ['residential', 'housing_society'],
    lat: 26.142,
    lng: 91.678,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-5',
    mainText: 'Subham Heights & Valley View Apartments',
    secondaryText: 'Gotanagar Hills, Jalukbari Road, Guwahati 781033',
    fullText: 'Subham Heights & Valley View, Gotanagar, Jalukbari',
    types: ['residential', 'housing_society'],
    lat: 26.146,
    lng: 91.685,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-6',
    mainText: 'Protech View Housing Complex',
    secondaryText: 'Bhetapara, Garchuk, Guwahati 781035',
    fullText: 'Protech View Housing Complex, Bhetapara/Garchuk',
    types: ['residential', 'housing_society'],
    lat: 26.128,
    lng: 91.745,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-7',
    mainText: 'Adabari Tiniali Residential Colony',
    secondaryText: 'Adabari, Jalukbari Road, Guwahati 781014',
    fullText: 'Adabari Residential Colony, Jalukbari, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.156,
    lng: 91.688,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-8',
    mainText: 'Maligaon Rest Camp Housing Colony',
    secondaryText: 'Rest Camp Road, Maligaon, Guwahati 781011',
    fullText: 'Maligaon Rest Camp Housing Society, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.161,
    lng: 91.704,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-9',
    mainText: 'Gotanagar Railway Housing Colony',
    secondaryText: 'Gotanagar, Maligaon/Jalukbari, Guwahati 781011',
    fullText: 'Gotanagar Railway Housing Society, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.152,
    lng: 91.694,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-10',
    mainText: 'Dharapur Residential Enclave',
    secondaryText: 'Dharapur Chariali, Airport Road, Guwahati 781017',
    fullText: 'Dharapur Residential Enclave, Airport Road',
    types: ['residential', 'housing_society'],
    lat: 26.136,
    lng: 91.625,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-11',
    mainText: 'Spanish Garden Residential Complex',
    secondaryText: 'Zoo Road, RGB Road, Ambikagirinagar, Guwahati 781024',
    fullText: 'Spanish Garden Apartment Complex, Zoo Road, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.172,
    lng: 91.778,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-12',
    mainText: 'Regal Residency Apartments',
    secondaryText: 'Six Mile, VIP Road, Guwahati 781022',
    fullText: 'Regal Residency Apartments, Six Mile, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.133,
    lng: 91.807,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-13',
    mainText: 'Green Valley Housing Society',
    secondaryText: 'Narengi VIP Road, Guwahati 781026',
    fullText: 'Green Valley Housing Society, Narengi, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.201,
    lng: 91.824,
    category: 'housing',
  },
  {
    placeId: 'jaluk-soc-14',
    mainText: 'Narengi Tiniali & Housing Colony',
    secondaryText: 'Narengi, VIP Road, Guwahati 781026',
    fullText: 'Narengi Tiniali & Housing Colony, Guwahati',
    types: ['residential', 'housing_society'],
    lat: 26.202,
    lng: 91.825,
    category: 'housing',
  },

  // ==========================================
  // 3. JALUKBARI & GUWAHATI MALLS & SHOPPING
  // ==========================================
  {
    placeId: 'jaluk-mall-1',
    mainText: 'Adabari Central Supermarket & Daily Bazar',
    secondaryText: 'Adabari Bus Stand, AT Road, Guwahati 781014',
    fullText: 'Adabari Central Supermarket, Jalukbari Area',
    types: ['shopping_mall', 'supermarket'],
    lat: 26.1555,
    lng: 91.686,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-2',
    mainText: 'Maligaon Daily Market & Reliance Trends',
    secondaryText: 'Maligaon Chariali, AT Road, Guwahati 781011',
    fullText: 'Reliance Trends & Market, Maligaon, Guwahati',
    types: ['shopping_mall', 'store'],
    lat: 26.159,
    lng: 91.702,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-3',
    mainText: 'V-Mart Shopping Mall Maligaon',
    secondaryText: 'Pandu Port Road, Maligaon, Guwahati 781011',
    fullText: 'V-Mart Mall, Maligaon, Guwahati',
    types: ['shopping_mall', 'store'],
    lat: 26.163,
    lng: 91.701,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-4',
    mainText: 'City Centre Mall Guwahati',
    secondaryText: 'GS Road, Christian Basti, Guwahati 781005',
    fullText: 'City Centre Mall, GS Road, Guwahati',
    types: ['shopping_mall', 'establishment'],
    lat: 26.158,
    lng: 91.776,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-5',
    mainText: 'Aurus Mall & PVR Cinemas',
    secondaryText: 'GS Road, Dispur, Guwahati 781006',
    fullText: 'Aurus Mall, Dispur, GS Road, Guwahati',
    types: ['shopping_mall', 'establishment'],
    lat: 26.143,
    lng: 91.791,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-6',
    mainText: 'Roodraksh Mall',
    secondaryText: 'Bhangagarh, GS Road, Guwahati 781005',
    fullText: 'Roodraksh Mall, Bhangagarh, Guwahati',
    types: ['shopping_mall', 'establishment'],
    lat: 26.162,
    lng: 91.765,
    category: 'mall',
  },
  {
    placeId: 'jaluk-mall-7',
    mainText: 'Central Mall & Inox',
    secondaryText: 'Christian Basti, GS Road, Guwahati 781005',
    fullText: 'Central Mall, Christian Basti, Guwahati',
    types: ['shopping_mall', 'establishment'],
    lat: 26.156,
    lng: 91.777,
    category: 'mall',
  },

  // ==========================================
  // 4. JALUKBARI CAMPUS, HOSTELS & INSTITUTIONS
  // ==========================================
  {
    placeId: 'jaluk-camp-1',
    mainText: 'Gauhati University (GU Main Campus)',
    secondaryText: 'Jalukbari, Guwahati, Assam 781014',
    fullText: 'Gauhati University Main Campus, Jalukbari',
    types: ['university', 'establishment'],
    lat: 26.152,
    lng: 91.664,
    category: 'campus',
  },
  {
    placeId: 'jaluk-camp-2',
    mainText: 'Assam Engineering College (AEC Campus & Hostels)',
    secondaryText: 'AEC Road, Jalukbari, Guwahati 781013',
    fullText: 'Assam Engineering College, Jalukbari, Guwahati',
    types: ['university', 'establishment'],
    lat: 26.143,
    lng: 91.662,
    category: 'campus',
  },
  {
    placeId: 'jaluk-camp-3',
    mainText: 'Gauhati University BKB Hall & Hostels',
    secondaryText: 'GU North Campus, Jalukbari, Guwahati 781014',
    fullText: 'GU BKB Hall & Hostels, Jalukbari, Guwahati',
    types: ['university', 'hostel'],
    lat: 26.155,
    lng: 91.661,
    category: 'campus',
  },
  {
    placeId: 'jaluk-camp-4',
    mainText: 'Bhupen Hazarika Samadhi Kshetra',
    secondaryText: 'Jalukbari Rotary Point, NH-27, Guwahati 781014',
    fullText: 'Bhupen Hazarika Memorial, Jalukbari, Guwahati',
    types: ['tourist_attraction', 'landmark'],
    lat: 26.1495,
    lng: 91.667,
    category: 'campus',
  },
  {
    placeId: 'jaluk-camp-5',
    mainText: 'Lankeshwar Temple & Market',
    secondaryText: 'Jalukbari - Paschim Boragaon Road, Guwahati 781014',
    fullText: 'Lankeshwar Temple & Market, Jalukbari',
    types: ['hindu_temple', 'landmark'],
    lat: 26.144,
    lng: 91.654,
    category: 'campus',
  },
  {
    placeId: 'jaluk-camp-6',
    mainText: 'Saraighat Bridge & Brahmaputra View Point',
    secondaryText: 'Jalukbari North, Amingaon Connect, Guwahati 781014',
    fullText: 'Saraighat Bridge View Point, Jalukbari, Guwahati',
    types: ['bridge', 'landmark'],
    lat: 26.168,
    lng: 91.674,
    category: 'campus',
  },

  // ==========================================
  // 5. JALUKBARI & GUWAHATI HOSPITALS & POLICE
  // ==========================================
  {
    placeId: 'jaluk-hosp-1',
    mainText: 'Government Ayurvedic College & Hospital',
    secondaryText: 'Jalukbari Rotary, Jalukbari, Guwahati 781014',
    fullText: 'Ayurvedic College & Hospital, Jalukbari, Guwahati',
    types: ['hospital', 'health'],
    lat: 26.1502,
    lng: 91.6655,
    category: 'hospital',
  },
  {
    placeId: 'jaluk-hosp-2',
    mainText: 'Excelcare Superspeciality Hospital',
    secondaryText: 'NH-37, Paschim Boragaon, Near Jalukbari, Guwahati 781033',
    fullText: 'Excelcare Superspeciality Hospital, Paschim Boragaon',
    types: ['hospital', 'health'],
    lat: 26.136,
    lng: 91.681,
    category: 'hospital',
  },
  {
    placeId: 'jaluk-hosp-3',
    mainText: 'Sanjeevani Hospital & Diagnostic Centre',
    secondaryText: 'Maligaon Chariali, Near Jalukbari, Guwahati 781011',
    fullText: 'Sanjeevani Hospital, Maligaon, Guwahati',
    types: ['hospital', 'health'],
    lat: 26.1585,
    lng: 91.703,
    category: 'hospital',
  },
  {
    placeId: 'jaluk-hosp-4',
    mainText: 'Swagat Superspeciality Surgical Hospital',
    secondaryText: 'AT Road, Maligaon Gate No. 3, Guwahati 781011',
    fullText: 'Swagat Superspeciality Hospital, Maligaon, Guwahati',
    types: ['hospital', 'health'],
    lat: 26.157,
    lng: 91.698,
    category: 'hospital',
  },
  {
    placeId: 'jaluk-hosp-5',
    mainText: 'Ayursundra Superspeciality Hospital',
    secondaryText: 'Gorchuk, NH-37, ISBT Road, Guwahati 781035',
    fullText: 'Ayursundra Superspeciality Hospital, Gorchuk, Guwahati',
    types: ['hospital', 'health'],
    lat: 26.1265,
    lng: 91.732,
    category: 'hospital',
  },
  {
    placeId: 'jaluk-pol-1',
    mainText: 'Jalukbari Police Station',
    secondaryText: 'Jalukbari Rotary Point, NH-27, Guwahati 781014',
    fullText: 'Jalukbari Police Station, Jalukbari, Guwahati',
    types: ['police', 'establishment'],
    lat: 26.1498,
    lng: 91.6668,
    category: 'police',
  },
  {
    placeId: 'jaluk-pol-2',
    mainText: 'Maligaon Police Outpost & Station',
    secondaryText: 'Maligaon Chariali, AT Road, Guwahati 781011',
    fullText: 'Maligaon Police Station, Maligaon, Guwahati',
    types: ['police', 'establishment'],
    lat: 26.1592,
    lng: 91.701,
    category: 'police',
  },
  {
    placeId: 'jaluk-pol-3',
    mainText: 'Gorchuk Police Station',
    secondaryText: 'Gorchuk Chariali, NH-37, Guwahati 781035',
    fullText: 'Gorchuk Police Station, Gorchuk, Guwahati',
    types: ['police', 'establishment'],
    lat: 26.129,
    lng: 91.735,
    category: 'police',
  },
  {
    placeId: 'jaluk-pol-4',
    mainText: 'All Women Police Station Panbazar',
    secondaryText: 'Panbazar Police Reserve, Guwahati 781001',
    fullText: 'All Women Police Station, Panbazar, Guwahati',
    types: ['police', 'establishment'],
    lat: 26.187,
    lng: 91.748,
    category: 'police',
  },
]
